-- CREATE TABLE users
-- (
--     id  SERIAL PRIMARY KEY,
--     login VARCHAR(255),
--     role VARCHAR(255)
-- );
--
-- INSERT INTO users (login, password, role)
-- VALUES ('lucas', '12345678', 'ADMIN');